//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasasRed_Nuevo3_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CasasRedEntities : DbContext
    {
        public CasasRedEntities()
            : base("name=CasasRedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Contaduria> Contaduria { get; set; }
        public virtual DbSet<Corretaje> Corretaje { get; set; }
        public virtual DbSet<Gestion> Gestion { get; set; }
        public virtual DbSet<Habilitacion> Habilitacion { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Verificacion> Verificacion { get; set; }
        public virtual DbSet<Articulos> Articulos { get; set; }
    }
}
