//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasasRed_Nuevo3_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contaduria
    {
        public int Id { get; set; }
        public Nullable<decimal> Cnt_M_Preguntar { get; set; }
        public Nullable<decimal> Cnt_Material { get; set; }
        public Nullable<decimal> Cnt_Vigilancia { get; set; }
        public Nullable<decimal> Cnt_Tramites { get; set; }
        public Nullable<decimal> Cnt_CESPT { get; set; }
        public Nullable<decimal> Cnt_CFE { get; set; }
        public Nullable<int> Id_Corretaje { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<decimal> Cnt_DevMensualidad { get; set; }
        public Nullable<System.DateTime> Cnt_FechaAlta { get; set; }
    
        public virtual Corretaje Corretaje { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
