//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasasRed_Nuevo3_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contaduria
    {
        public int Id { get; set; }
        public Nullable<decimal> Cnt_Presupuesto_gestion { get; set; }
        public Nullable<decimal> Cnt_Presupuesto_corretaje { get; set; }
        public Nullable<decimal> Cnt_Presupuesto_habilitacion { get; set; }
        public Nullable<decimal> Cnt_Mensualidad { get; set; }
        public Nullable<decimal> Cnt_Vigilancia { get; set; }
    
        public virtual Corretaje Corretaje { get; set; }
        public virtual Gestion Gestion { get; set; }
        public virtual Habilitacion Habilitacion { get; set; }
    }
}
