//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasasRed_Nuevo3_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Corretaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Corretaje()
        {
            this.Contaduria = new HashSet<Contaduria>();
            this.Gestion = new HashSet<Gestion>();
            this.Habilitacion = new HashSet<Habilitacion>();
        }
    
        public int Id { get; set; }

        [RegularExpression("^[a-zA-Z]+\\s*([a-zA-Z]*\\s*)*$", ErrorMessage = "Verificar")]
        public string Crt_Status { get; set; }

        [RegularExpression("^[a-zA-Z]+\\s*([a-zA-Z]*\\s*)*$", ErrorMessage = "Verificar Nombre")]
        public string Crt_Cliente_Nombre { get; set; }

        [RegularExpression("^[a-zA-Z]+\\s*([a-zA-Z]*\\s*)*$", ErrorMessage = "Verificar Apellido")]
        public string Crt_Cliente_ApMat { get; set; }

        [RegularExpression("^[a-zA-Z]+\\s*([a-zA-Z]*\\s*)*$", ErrorMessage = "Verificar Apellido")]
        public string Crt_Cliente_ApPat { get; set; }

        [RegularExpression("^[a-zA-Z0-9]+\\s*([a-zA-Z0-9]*\\s*)*$", ErrorMessage = "Verificar direccion")]
        public string Crt_Direccion { get; set; }

        [RegularExpression("^\\d+$", ErrorMessage = "Revisar")]
        public string Crt_Precio { get; set; }

        [RegularExpression("^\\d+$", ErrorMessage = "Revisar")]
        public string Crt_Gasto { get; set; }

        [RegularExpression("^[a-zA-Z]+\\s*([a-zA-Z]*\\s*)*$", ErrorMessage = "Verificar")]
        public string Crt_Tipo_Vivienda { get; set; }

        [RegularExpression("\\d+", ErrorMessage = "solo números")]
        public Nullable<int> Crt_Nivel { get; set; }

        [RegularExpression("\\d+", ErrorMessage = "solo números")]
        public Nullable<int> Crt_Num_Habitaciones { get; set; }

        [RegularExpression("\\d+", ErrorMessage = "solo números")]
        public Nullable<int> Crt_Planta { get; set; }


        public Nullable<System.DateTime> Crt_Ano_compra { get; set; }

        [RegularExpression("\\d+", ErrorMessage = "solo números")]
        public string Crt_Num_Credito_Infonavit { get; set; }

        [RegularExpression("^\\d+[.]*\\d*$", ErrorMessage = "solo números")]
        public Nullable<decimal> Crt_Saldo_infonavit { get; set; }

        public Nullable<System.DateTime> Crt_Fec_Nac { get; set; }

        [RegularExpression("\\d+", ErrorMessage = "Verificar número")]
        public Nullable<int> Crt_Tel_Celular { get; set; }

        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Verificar estado civil")]
        public string Crt_Estado_Civil { get; set; }

        [RegularExpression("\\d+", ErrorMessage = "Verificar número")]
        public string Crt_Tel_Casa { get; set; }

        [RegularExpression("\\d+", ErrorMessage = "Verificar número")]
        public string Crt_Tel_Trabajo { get; set; }

        [RegularExpression("\\d+", ErrorMessage = "Verificar número")]
        public string Crt_Tel_Ref1 { get; set; }

        [RegularExpression("\\d+", ErrorMessage = "Verificar número")]
        public string Crt_Tel_Ref2 { get; set; }

        [RegularExpression("\\d+", ErrorMessage = "Verificar número")]
        public string Crt_Tel_Ref { get; set; }

        public Nullable<bool> Crt_Recibo_predial_digital { get; set; }

        [RegularExpression("^[a-zA-Z0-9]+\\s*([a-zA-Z0-9]*\\s*)*$", ErrorMessage = "Verificar clave")]
        public string Crt_Clave_Catastral { get; set; }

        [RegularExpression("^\\d+[.]*\\d*$", ErrorMessage = "solo números")]
        public Nullable<decimal> Crt_Adeudo_predial { get; set; }

        public Nullable<bool> Crt_Recibo_luz_digitalizar { get; set; }

        [RegularExpression("^\\d+$", ErrorMessage = "solo números")]
        public string Crt_Num_servicio_luz { get; set; }

        [RegularExpression("^\\d+[.]*\\d*$", ErrorMessage = "solo números")]
        public Nullable<decimal> Crt_Adeudo_luz { get; set; }

        [RegularExpression("^[a-zA-Z]+\\s*([a-zA-Z]*\\s*)*$", ErrorMessage = "Verificar Nombre")]
        public string Crt_NombreC_Titular_luz { get; set; }

        public Nullable<bool> Crt_Recibo_agua_digital { get; set; }

        [RegularExpression("^\\d+$", ErrorMessage = "solo números")]
        public string Crt_No_cuenta_agua { get; set; }

        [RegularExpression("^\\d+[.]*\\d*$", ErrorMessage = "solo números")]
        public Nullable<decimal> Crt_Adeudo_agua { get; set; }

        public Nullable<bool> Crt_Ine_Titu { get; set; }
        public Nullable<bool> Crt_Ine_Conyu { get; set; }
        public Nullable<bool> Crt_Escritura_Simple { get; set; }
        public Nullable<bool> Crt_Acuerdo { get; set; }
        public Nullable<bool> Crt_ActaNacTitu { get; set; }
        public Nullable<bool> Crt_ActaNacConyu { get; set; }
        public Nullable<bool> Crt_ActaMatr { get; set; }
        public Nullable<bool> Crt_EscrCert { get; set; }
        public Nullable<bool> Crt_CartaDesPre { get; set; }
        public Nullable<bool> Crt_ReciboLuz { get; set; }
        public Nullable<bool> Crt_ReciboAgua { get; set; }
        public Nullable<bool> Crt_Otros { get; set; }

        [RegularExpression("^[a-zA-Z]+\\s*([a-zA-Z]*\\s*)*$", ErrorMessage = "Verificar")]
        public string Crt_Status_Muestra { get; set; }

        [RegularExpression("^[a-zA-Z0-9]+\\s*([a-zA-Z0-9]*\\s*)*$", ErrorMessage = "Verificar")]
        public string Crt_Obervaciones { get; set; }

        [RegularExpression("^\\d+[.]*\\d*$", ErrorMessage = "solo números")]
        public Nullable<decimal> Crt_GastosServicios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contaduria> Contaduria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestion> Gestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habilitacion> Habilitacion { get; set; }
    }
}
