//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasasRed_Nuevo3_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotosHabilitacion
    {
        public int fh_id { get; set; }
        public string fh_archivo { get; set; }
        public string fh_nombre { get; set; }
        public Nullable<int> fh_habilitacion { get; set; }
    
        public virtual Habilitacion Habilitacion { get; set; }
    }
}
