//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasasRed_Nuevo3_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosContaduria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GastosContaduria()
        {
            this.Contaduria = new HashSet<Contaduria>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> GstCon_Mensualidad { get; set; }
        public Nullable<decimal> GstCon_Vigilancia { get; set; }
        public Nullable<decimal> GstCon_Otros { get; set; }
        public Nullable<int> Id_Corretaje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contaduria> Contaduria { get; set; }
        public virtual Corretaje Corretaje { get; set; }
    }
}
