//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasasRed_Nuevo3_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int Id { get; set; }
        public Nullable<int> Not_usuario_id { get; set; }
        public string Not_titutlo { get; set; }
        public string Not_descripcion { get; set; }
        public string Not_idVinculado { get; set; }
        public Nullable<bool> Not_leida { get; set; }
        public Nullable<bool> Not_mostrada { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
