//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public string art_id { get; set; }
        public string art_nombre { get; set; }
        public string art_descripcion { get; set; }
        public Nullable<System.DateTime> art_fechaIngreso { get; set; }
        public Nullable<decimal> art_cantidadMinima { get; set; }
    }
}
