//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasaInventario
    {
        public int ci_Id { get; set; }
        public int ci_corretaje_id { get; set; }
        public decimal ci_cantidadAsignada { get; set; }
        public System.DateTime ci_fecha { get; set; }
        public int ci_usuario_id { get; set; }
        public string ci_articulo_id { get; set; }
    }
}
