//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CasasRedEntities : DbContext
    {
        public CasasRedEntities()
            : base("name=CasasRedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulos> Articulos { get; set; }
        public virtual DbSet<CalificacionVendedor> CalificacionVendedor { get; set; }
        public virtual DbSet<CasaInventario> CasaInventario { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Comentarios> Comentarios { get; set; }
        public virtual DbSet<Comision> Comision { get; set; }
        public virtual DbSet<Contaduria> Contaduria { get; set; }
        public virtual DbSet<Corretaje> Corretaje { get; set; }
        public virtual DbSet<DetallesComision> DetallesComision { get; set; }
        public virtual DbSet<Existencias> Existencias { get; set; }
        public virtual DbSet<FotosHabilitacion> FotosHabilitacion { get; set; }
        public virtual DbSet<GastosContaduria> GastosContaduria { get; set; }
        public virtual DbSet<Gestion> Gestion { get; set; }
        public virtual DbSet<Habilitacion> Habilitacion { get; set; }
        public virtual DbSet<HistorialAsignacion> HistorialAsignacion { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Ubicaciones> Ubicaciones { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<VendedorAsig> VendedorAsig { get; set; }
        public virtual DbSet<Verificacion> Verificacion { get; set; }
    }
}
