//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int Id { get; set; }
        public string Cmt_Titulo { get; set; }
        public string Cmt_Nota { get; set; }
        public Nullable<System.DateTime> Cmt_Fecha { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
