//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int Id { get; set; }
        public string Cmt_Titulo { get; set; }
        public string Cmt_Nota { get; set; }
        public Nullable<System.DateTime> Cmt_Fecha { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
    }
}
