//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesComision
    {
        public int Id { get; set; }
        public Nullable<int> Id_Vendedor { get; set; }
        public Nullable<int> Id_Comision { get; set; }
        public Nullable<decimal> DCms_Monto { get; set; }
        public string DCms_TipoCom { get; set; }
    }
}
