//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Existencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Existencias()
        {
            this.HistorialAsignacion = new HashSet<HistorialAsignacion>();
        }
    
        public int Id { get; set; }
        public string ext_art_id { get; set; }
        public Nullable<decimal> ext_cantidad { get; set; }
        public Nullable<decimal> ext_cantidadActual { get; set; }
        public Nullable<decimal> ext_precioUnitario { get; set; }
        public Nullable<System.DateTime> ext_fechaAgregado { get; set; }
        public Nullable<int> ext_usuarioAgrego { get; set; }
        public Nullable<int> ext_ubicacion { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialAsignacion> HistorialAsignacion { get; set; }
    }
}
