//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Existencias
    {
        public int Id { get; set; }
        public string ext_art_id { get; set; }
        public Nullable<decimal> ext_cantidad { get; set; }
        public Nullable<decimal> ext_cantidadActual { get; set; }
        public Nullable<decimal> ext_precioUnitario { get; set; }
        public Nullable<System.DateTime> ext_fechaAgregado { get; set; }
        public Nullable<int> ext_usuarioAgrego { get; set; }
        public Nullable<int> ext_ubicacion { get; set; }
    }
}
