//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosContaduria
    {
        public int Id { get; set; }
        public string GstCon_Concepto { get; set; }
        public Nullable<decimal> GstCon_Monto { get; set; }
        public string GstCon_Descripcion { get; set; }
        public Nullable<System.DateTime> GstCon_Fecha { get; set; }
        public Nullable<int> Id_Corretaje { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
    }
}
