//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habilitacion
    {
        public int Id { get; set; }
        public Nullable<bool> Hbt_Puertas { get; set; }
        public Nullable<bool> Hbt_Chapas { get; set; }
        public Nullable<bool> Hbt_Marcos_puertas { get; set; }
        public Nullable<bool> Hbt_Bisagras { get; set; }
        public Nullable<bool> Hbt_Taza { get; set; }
        public Nullable<bool> Hbt_Lavamanos { get; set; }
        public Nullable<bool> Hbt_Bastago { get; set; }
        public Nullable<bool> Hbt_Chapeton { get; set; }
        public Nullable<bool> Hbt_Maneral { get; set; }
        public Nullable<bool> Hbt_Regadera_completa { get; set; }
        public Nullable<bool> Hbt_Kit_lavamanos { get; set; }
        public Nullable<bool> Hbt_Kit_taza { get; set; }
        public Nullable<bool> Hbt_Rosetas { get; set; }
        public Nullable<bool> Hbt_Apagador_sencillo { get; set; }
        public Nullable<bool> Hbt_Conector_sencillo { get; set; }
        public Nullable<bool> Hbt_Apagador_doble { get; set; }
        public Nullable<bool> Hbt_Conector_apagador { get; set; }
        public Nullable<bool> Hbt_Domo { get; set; }
        public Nullable<bool> Hbt_Ventanas { get; set; }
        public Nullable<bool> Hbt_Cableado { get; set; }
        public string Hbt_Calibre_cableado { get; set; }
        public Nullable<bool> Hbt_Break_interior { get; set; }
        public Nullable<bool> Hbt_Break_medidor { get; set; }
        public Nullable<bool> Hbt_Pinturas { get; set; }
        public Nullable<bool> Hbt_AvisoSusp { get; set; }
        public string Hbt_StatusCasa { get; set; }
        public Nullable<System.DateTime> Hbt_FchEntrega { get; set; }
        public Nullable<int> Hbt_ProgresoForm { get; set; }
        public Nullable<int> Id_Corretaje { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<System.DateTime> Hbt_FechaAlta { get; set; }
    }
}
