//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialAsignacion
    {
        public int ha_id { get; set; }
        public Nullable<int> ha_casaInventario { get; set; }
        public int ha_existencia_id { get; set; }
        public Nullable<int> ha_usuarioEntrego { get; set; }
    }
}
