//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int Id { get; set; }
        public Nullable<int> Not_usuario_id { get; set; }
        public string Not_titutlo { get; set; }
        public string Not_descripcion { get; set; }
        public string Not_idVinculado { get; set; }
        public Nullable<bool> Not_leida { get; set; }
        public Nullable<bool> Not_mostrada { get; set; }
    }
}
