//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordatorio
    {
        public int Rcd_Id { get; set; }
        public Nullable<int> Rcd_Id_Usuario { get; set; }
        public Nullable<int> Rcd_Id_Gestion { get; set; }
        public Nullable<bool> Rcd_Enviado { get; set; }
        public string Rcd_Titulo { get; set; }
        public string Rcd_Descripcion { get; set; }
        public Nullable<int> Rcd_Anio { get; set; }
        public Nullable<int> Rcd_Mes { get; set; }
        public Nullable<int> Rcd_Dia { get; set; }
        public Nullable<int> Rcd_Hora { get; set; }
        public Nullable<int> Rcd_Minuto { get; set; }
        public Nullable<bool> Rcd_Listado { get; set; }
    }
}
