//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string usu_username { get; set; }
        public string usu_correo { get; set; }
        public string usu_nombre { get; set; }
        public string usu_password { get; set; }
        public string usu_apellidoPa { get; set; }
        public string usu_apellidoMa { get; set; }
        public Nullable<System.DateTime> usu_alta { get; set; }
        public string usu_tipo { get; set; }
        public Nullable<bool> usu_activo { get; set; }
        public Nullable<int> Id_TipoUsiario { get; set; }
    }
}
