//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        public int Id { get; set; }
        public string Vndr_Nombre { get; set; }
        public string Vndr_Apellidopa { get; set; }
        public string Vndr_Apellidoma { get; set; }
    }
}
