//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verificacion
    {
        public int Id { get; set; }
        public Nullable<bool> Vfn_Persona_fisica { get; set; }
        public Nullable<bool> Vfn_Visto_persona { get; set; }
        public Nullable<bool> Vfn_Tiempo_estimado { get; set; }
        public string Vfn_Tiempo { get; set; }
        public Nullable<bool> Vfn_Tiene_costo { get; set; }
        public Nullable<decimal> Vfn_Costo { get; set; }
        public Nullable<int> Vfn_Trato_asesor { get; set; }
        public string Vfn_Observaciones { get; set; }
        public Nullable<int> Vfn_ProgresoForm { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<System.DateTime> Vfn_FechaAlta { get; set; }
    }
}
